name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy_to_production:
    name: Connect and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Connect And Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/django-ogcapif
            ./startup.sh
